### ISSUE TITLE
Support for JSON output?

### ISSUE THREAD

**Issue by plambert** [davidchalifoux/kaput-cli#1]
It'd be great if there could be a `--json` or `--output json` option that outputs a single json record per line, for the files and transfers commands that output a table.

**Comment by davidchalifoux** [comment]
Good idea! Just to clarify, do you want it to output JSON to stdout or to a file?

**Comment by plambert** [comment]
stdout is great.  requiring a file name prevents using stdout, whereas without it, the user still can write to a file.

typically, a list can be produced as a valid json array (`[{...},{...},{...}]`) or a list of json objects one-per-line (`{...}\n{...}\n{...}\n`).

I personally prefer the latter.  One could make it an option, but there are tools for manipulating JSON like `jq` that will always have more features, so why not just tell people to use `jq` to convert or modify the output JSON?

Paul

**Comment by davidchalifoux** [comment]
I've added this in commit https://github.com/davidchalifoux/kaput-cli/commit/e8fb214f317b5c3f86778552fc8bd712d34e4d4c.

Passing the `--json` flag will output in pure JSON. I've also tested it with `jq` and it works nicely!
The output it gives is _all_ of the data that is returned by the API. Was this the extra metadata you were looking for?

**Comment by davidchalifoux** [comment]
Also added the flag to `transfers`. https://github.com/davidchalifoux/kaput-cli/commit/a61b5aa9df81bcac33f2d129baa973755f18c8e9
