### ISSUE TITLE
transfer:add with folderID flag not working as expected

### ISSUE THREAD

**Issue by rajivravio** [davidchalifoux/kaput-cli#30]
Adding the folderID flag still download to root directory in putio

transfer:add --folderID=<folderID> <magnet_url>
transfer:add -f<folderID> <magnet_url>

**Comment by davidchalifoux** [comment]
Hey @rajivravio 
Could you confirm that you are including a folder ID when you are using that command?
The examples you gave should look like `transfers:add --folderID=<folderID> <URL>` (note no space after `folderID=`).

**Comment by davidchalifoux** [comment]
This was re-added in v2.3.0. Let me know if you have any issues with it.
