### ISSUE TITLE
Listing transfers with active transfer causes error

### ISSUE THREAD

**Issue by joshkerr** [davidchalifoux/kaput-cli#37]
I started a transfer and then, in a new terminal window, tried to list transfers and got this error:

thread 'main' panicked at 'fetching transfers: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected u32", line: 1, column: 1268) }', /Users/joshkerr/.cargo/registry/src/github.com-1ecc6299db9ec823/kaput-cli-2.0.0/src/main.rs:473:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by joshkerr** [comment]
Here is the full backtrace:

RUST_BACKTRACE=full kaput transfers list
thread 'main' panicked at 'fetching transfers: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected u32", line: 1, column: 314) }', /Users/joshkerr/.cargo/registry/src/github.com-1ecc6299db9ec823/kaput-cli-2.0.0/src/main.rs:473:60
stack backtrace:
   0:        0x100f6989c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf92d0b9100685592
   1:        0x100f87254 - core::fmt::write::hba950d59ddceeaaa
   2:        0x100f59e8c - std::io::Write::write_fmt::h9e52517f23e48360
   3:        0x100f696ac - std::sys_common::backtrace::print::hd205fa5e4b881c8b
   4:        0x100f5a85c - std::panicking::default_hook::{{closure}}::h1fc0ab063b55fdaf
   5:        0x100f5a520 - std::panicking::default_hook::h68f99660ab2cf986
   6:        0x100f5b0d8 - std::panicking::rust_panic_with_hook::haf8b9b224847163e
   7:        0x100f69f60 - std::panicking::begin_panic_handler::{{closure}}::h71de5f2fd48a9ed8
   8:        0x100f69994 - std::sys_common::backtrace::__rust_end_short_backtrace::h95cd4256776145cf
   9:        0x100f5acec - _rust_begin_unwind
  10:        0x100f9b3e4 - core::panicking::panic_fmt::h03053be4fed319aa
  11:        0x100f9b718 - core::result::unwrap_failed::hbab326b6fd47affb
  12:        0x100d81154 - core::result::Result<T,E>::expect::h388dd663254cb137
  13:        0x100d87adc - kaput::main::h045a3ed5381ccaae
  14:        0x100d68570 - std::sys_common::backtrace::__rust_begin_short_backtrace::h040bfd19d9d8a64d
  15:        0x100d6486c - std::rt::lang_start::{{closure}}::hd5815d17933b6d9b
  16:        0x100f596f4 - std::rt::lang_start_internal::hcf5249aa241f98ab
  17:        0x100d896d4 - _main

**Comment by davidchalifoux** [comment]
@joshkerr I believe I fixed this. Try installing the latest version!
