### ISSUE TITLE
Play - new feature request to play videos using mpv.

### ISSUE THREAD

**Issue by joshkerr** [davidchalifoux/kaput-cli#38]
It would be nice to be able to type:

kaput files play ID

and have kaput launch mpv to start playing the requested video. Seems like an easy feature to add. You can reuse the download URL you already generate via "kaput files URL".

If you pass it a file, it plays the file. If you pass it a folder, it generates a playlist and plays the files in the folder that are video files.

**Comment by davidchalifoux** [comment]
This is a good suggestion!

I haven't heard of MPV before so I'll need to do some research, but it sounds very feasible. 

I'm not sure if generating a playlist is possible because I'm pretty sure the generated links expire, but I'll look into it.

**Comment by davidchalifoux** [comment]
@joshkerr I added the `play` command in the latest version, please update and let me know how it goes!

I still don't think generating playlists will work because IIRC the generated links expire.

**Comment by joshkerr** [comment]
Thanks, works great. Appreciate you adding that.
