### ISSUE TITLE
Upload parent directory

### ISSUE THREAD

**Issue by bdmorin** [davidchalifoux/kaput-cli#43]
Is it possible to specify the parent directory you want putio to put the completed file after a `kaput file upload`?

Right now it all goes to my default folder, but I'd like to go to a specific putio folder.

I saw the previous issue #6 and there's an option in there for `parent_id=` however I don't see how to use it on the CLI.

Thank you for a cool tool!

**Comment by davidchalifoux** [comment]
Yeah I haven't added that feature in the upload command yet.
I can add it once I have some availability.

**Comment by bdmorin** [comment]
Still learning rust, wasn't able to tackle this myself.

**Comment by bdmorin** [comment]
Do you think we could have an argument that let's us pass parameters to curl? like `-s` if we don't need output? I tried using env vars, but it didn't seem to take.

**Comment by davidchalifoux** [comment]
These features have been added in #44! Let me know if there are other CURL arguments you'd like to be able to pass through.

**Comment by bdmorin** [comment]
Awesome! Thank you!
