### ISSUE TITLE
Download folder throws error during check zip status "invalid type: null, expected a string"

### ISSUE THREAD

**Issue by kylepmanuel** [davidchalifoux/kaput-cli#48]
Release v2.1.1 file kaput-x86_64-unknown-linux-gnu.tar.gz

```kaput files download FILE_ID```

    Creating ZIP...
    thread 'main' panicked at src/put/zips.rs:25:70:
    checking zip status: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 25) }
     0:     0x5629045f520c - <unknown>
     1:     0x56290462245c - <unknown>
     2:     0x5629045f198e - <unknown>
     3:     0x5629045f4ff4 - <unknown>
     4:     0x5629045f66a3 - <unknown>
     5:     0x5629045f63bc - <unknown>
     6:     0x5629045f6c29 - <unknown>
     7:     0x5629045f6b27 - <unknown>
     8:     0x5629045f5736 - <unknown>
     9:     0x5629045f6872 - <unknown>
    10:     0x5629040cd833 - <unknown>
    11:     0x5629040cdc3a - <unknown>
    12:     0x5629041132f5 - <unknown>
    13:     0x5629040ec9dc - <unknown>
    14:     0x56290410b923 - <unknown>
    15:     0x5629041105b9 - <unknown>
    16:     0x5629045ec1db - <unknown>
    17:     0x5629040ed585 - <unknown>
    18:     0x7fec9c029d90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    19:     0x7fec9c029e40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    20:     0x5629040cdef5 - <unknown>
    21:                0x0 - <unknown>

**Comment by davidchalifoux** [comment]
Thanks for the report!

I believe I fixed this in the latest release, please update and give it a try.

Feel free to re-open if you are still having issues.

**Comment by kylepmanuel** [comment]
Confirmed 2.1.3 now works
