### ISSUE TITLE
Upload from CLI

### ISSUE THREAD

**Issue by davidchalifoux** [davidchalifoux/kaput-cli#6]
It'd be nice to be able to also upload files to Put from the CLI.

**Comment by davidchalifoux** [comment]
This is not currently possible using only the Put.js library.

**Comment by Gex2501** [comment]
Is it possible to upload a .torrent file to start the transfer?

**Comment by Gex2501** [comment]
That's fantastic! What I'm really looking for a simple one line curl command to add torrent transfers. I've been reading over the API for hours and I'm just not sure how to do it. I got the following from the API but where do I put my token so the command is authenticated?

`curl -X 'POST' \
  'https://upload.put.io/v2/files/upload' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@TotallyLegalFile.torrent' \
  -F 'filename=' \
  -F 'parent_id=0'`

**Comment by davidchalifoux** [comment]
@Gex2501 You're super close!

You just need an API token in the header:
`Authorization: Bearer ${API_TOKEN}`

Which I think looks like `-H "Authorization: Bearer TOKEN_HERE"` added to CURL.

**Comment by Gex2501** [comment]
Thank you so much! I spent hours trying to figure this out! This worked for me...
```
curl -X 'POST' \
  'https://upload.put.io/v2/files/upload' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Authorization: Bearer XXXXXXXTOKENXXXXXXXX' \
  -F 'file=@TotallyLegitFile.torrent' \
  -F 'filename=' \
  -F 'parent_id='
```
