### ISSUE TITLE
Need to fetch parent folder of fileid

### ISSUE THREAD

**Issue by DailenG** [davidchalifoux/kaput-cli#9]
I'm writing a script to categorize downloaded items, but to properly do so I need the parent folder info. Running kaput files obviously gets items whose parent_id equals the designated id, but getting the parent_id of the designated id would be great. Maybe a flag "--self" that could output the data for the ID instead of the contents?

My alternative has been to loop through folders until it finds one with that ID to determine the parent folder ID.

**Comment by davidchalifoux** [comment]
From my understanding, if `kaput files [ID]` is a folder, you want the details of the folder itself and not the contents?

I could probably add this in this weekend for ya.

**Comment by davidchalifoux** [comment]
@DailenG I added a `--self` flag to the `files list` command, give it a try and let me know if that works for you
